### ISSUE TITLE
Error during execution of "make run"

### ISSUE THREAD

**Issue by jacobw93-dev** [stevekm/image-sort#1]
Hello @stevekm,

I'm having difficulties on the step with executing `make run`. I'm getting such error message:
![image](https://user-images.githubusercontent.com/62847554/145998640-5fd74493-6ac9-49a8-99ae-2c0e21a260f7.png)

Could You provide me some information how to solve that?

**Comment by stevekm** [comment]
Hi @jacobw93-dev , not sure how it happened but your file `nextflow.config` appears to have gotten renamed to just `nextflow`. Try fixing the filename, then re run the `make conda-install` command. The current repo configuration installs the Nextflow executable in the current directory under the filename `nextflow`. Thus the error you're seeing.

**Comment by jacobw93-dev** [comment]
I think I've tried previously running "make run" with "nextflow.config" file, and then the error said that the "nextflow" file was missing, that's why I've removed the extension. But will try Your advice, however when I'm running "make conda-install" second time the process hangs at the "collecting package metadata" step... Do You know how long that could take?
![image](https://user-images.githubusercontent.com/62847554/146028268-f5f1756f-5dc7-44d4-b0fe-6cc4b425a2df.png)

**Comment by jacobw93-dev** [comment]
I've started process from the beginning and now during "make conda-install" and "make run" such errors occured:
![image](https://user-images.githubusercontent.com/62847554/146031510-64d7bfb8-4b82-4b18-83aa-bf3d6e1e12a8.png)

**Comment by jacobw93-dev** [comment]
Hi @stevekm , I have tried to set environment on VM (Ubuntu), but still cannot get through `make conda-install`:
![image](https://user-images.githubusercontent.com/62847554/146268973-85bae535-09e4-4838-bcd2-0cad20d02f44.png)
I've installed python 2.7.18. I would appreciate your help!

**Comment by stevekm** [comment]
It says the process was 'killed', did you try to cancel it while it was running? Otherwise I'm not entirely sure why it would die, perhaps your system is low on memory?

**Comment by jacobw93-dev** [comment]
Ok, I think there is small progress, but this time some requirements for the packages were not met:
![image](https://user-images.githubusercontent.com/62847554/146385300-d731cef4-b703-4461-926a-c1536fb89351.png)
Do You know how to install these manually?

**Comment by stevekm** [comment]
I am seeing the same error as well, looks like the available versions of conda packages might have changed since I last worked on this. Since you are already in Ubuntu, you can just try running something like  `sudo apt-get install imagemagick`, and remove that line from the `conda-install` recipe.

**Comment by stevekm** [comment]
@jacobw93-dev I have updated the Makefile to remove the installation for `imagemagick` which should help with this, you can manually install `imagemagick` yourself pretty easily. I also updated the Docker container for this repo so that you should also be able to just use it directly out of the container instead of having to install anything (see the notes about it in the updated README)

**Comment by jacobw93-dev** [comment]
Works like a charm! Thank You very much @stevekm for Your help :)

**Comment by stevekm** [comment]
hey just a heads up, I updated the program with a new release on version 2.0.0, see the updated README on the `master` branch for details. The program should be a lot easier to install and use now.

**Comment by jacobw93-dev** [comment]
Hi @stevekm, thank You very much, I appreciate Your job.
